Desktop version
Maria18000/Portfolio--setup-and-mobile-version-skeleton pull request #6
Opened 2022-06-03 15:40 UTC by Maria18000

Added Media Queries in the mobile version CSS

2022-06-03 16:41 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @Maria18000, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your README and PR message are descriptive ✔️

## Aspects to improve ♻️

- [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-03 16:41 UTC, leonardodiasb commented on styles.css
> +@media (min-width: 768px) {
- [ ] Kindly review all of your margins, paddings, font-sizes, heights and widths, and every other attribute that you used `vh` or `vw` for sizing and change for the values that the Figma template provides (px in most cases). This is causing distortion on some sizes of screens and making a bad user experience when scrolling through your app.
![image](https://user-images.githubusercontent.com/61919617/171906840-6a889a5b-4887-4a3e-9715-176cbe382ab1.png)
![image](https://user-images.githubusercontent.com/61919617/171906934-408aed0c-7ccd-4b66-9d54-084144f7a93a.png)
![image](https://user-images.githubusercontent.com/61919617/171906978-02a78d3f-66f8-458c-b4ed-954bb2853cfa.png)
![image](https://user-images.githubusercontent.com/61919617/171907052-4227b6be-e96f-4a7b-a44c-d5882e5b120e.png)
![image](https://user-images.githubusercontent.com/61919617/171907112-743de517-bf09-40fd-9666-f5434cda0b75.png)

2022-06-03 16:41 UTC, leonardodiasb commented on styles.css
> +  }
- [ ] Your regular projects should display a 'see project' button on hover. Kindly fix that.
![image](https://user-images.githubusercontent.com/61919617/171907384-f91191a0-0fd3-40d8-9846-20e980347cc8.png)

2022-06-03 16:41 UTC, leonardodiasb commented on styles.css
>  }
- [ ] Kindly correct the padding of your "See Project" on the desktop version.
![image](https://user-images.githubusercontent.com/61919617/171907737-5a416d24-b6cf-4f23-8b34-ad2012563d59.png)

2022-06-03 16:41 UTC, leonardodiasb commented on styles.css
> +}
- [ ] Your form margin/padding is not symmetrical. Kindly use the same dimensions the Figma template provides.
![image](https://user-images.githubusercontent.com/61919617/171908231-9af5f93a-a06f-4d38-a015-015d114adc56.png)
![image](https://user-images.githubusercontent.com/61919617/171908308-5f212d77-7a7b-4df9-9bd5-27e5b0a84e0c.png)

2022-06-03 18:14 UTC, Maria18000 commented
Hi Leonardo,

The see project button was not included in the figma template. It was on
first card only, and I had to remove it for the other cards.
Let me know if it still needs to be added so I can proceed...

On Fri, Jun 3, 2022, 9:41 PM Leonardo Dias Bussular <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> Required Changes ♻️ ⚠️ 🚦
>
> Hi @Maria18000 <https://github.com/Maria18000>,
>
> Good job so far!
> You still need to work on some issues to go to the next project, but you
> are almost there!
>
> [image: mario_ladders]
> <https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif>
> Good points 👍
>
> You used proper GitHub Flow ✔️
> Your linter checks are all passing ✔️
> Your README and PR message are descriptive ✔️
> Aspects to improve ♻️
>
>    - Check the comments under the review.
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think the code review was unfair, you can request a
> second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In styles.css
> <https://github.com/Maria18000/Portfolio--setup-and-mobile-version-skeleton/pull/6#discussion_r889133029>
> :
>
> > @@ -424,3 +431,303 @@ footer hr {
>
>    margin-top: 1vh;
>
>    padding-top: 0%;
>
>  }
>
> +
>
> ***@***.*** (min-width: 768px) {
>
>
>
>    - Kindly review all of your margins, paddings, font-sizes, heights and
>    widths, and every other attribute that you used vh or vw for sizing
>    and change for the values that the Figma template provides (px in most
>    cases). This is causing distortion on some sizes of screens and making a
>    bad user experience when scrolling through your app.
>    [image: image]
>    <https://user-images.githubusercontent.com/61919617/171906840-6a889a5b-4887-4a3e-9715-176cbe382ab1.png>
>    [image: image]
>    <https://user-images.githubusercontent.com/61919617/171906934-408aed0c-7ccd-4b66-9d54-084144f7a93a.png>
>    [image: image]
>    <https://user-images.githubusercontent.com/61919617/171906978-02a78d3f-66f8-458c-b4ed-954bb2853cfa.png>
>    [image: image]
>    <https://user-images.githubusercontent.com/61919617/171907052-4227b6be-e96f-4a7b-a44c-d5882e5b120e.png>
>    [image: image]
>    <https://user-images.githubusercontent.com/61919617/171907112-743de517-bf09-40fd-9666-f5434cda0b75.png>
>
> ------------------------------
>
> In styles.css
> <https://github.com/Maria18000/Portfolio--setup-and-mobile-version-skeleton/pull/6#discussion_r889134905>
> :
>
> > +  .card-body-head p {
>
> +    margin-top: 0%;
>
> +  }
>
>
>
>    - Your regular projects should display a 'see project' button on
>    hover. Kindly fix that.
>    [image: image]
>    <https://user-images.githubusercontent.com/61919617/171907384-f91191a0-0fd3-40d8-9846-20e980347cc8.png>
>
> ------------------------------
>
> In styles.css
> <https://github.com/Maria18000/Portfolio--setup-and-mobile-version-skeleton/pull/6#discussion_r889136456>
> :
>
> >  #see-project-small {
>
>    width: 18.5vh;
>
>    height: 7.3vh;
>
> -  margin: 0 5vh;
>
> +  margin-left: 0%;
>
>    font-size: 2.58vh;
>
>  }
>
>
>
>    - Kindly correct the padding of your "See Project" on the desktop
>    version.
>    [image: image]
>    <https://user-images.githubusercontent.com/61919617/171907737-5a416d24-b6cf-4f23-8b34-ad2012563d59.png>
>
> ------------------------------
>
> In styles.css
> <https://github.com/Maria18000/Portfolio--setup-and-mobile-version-skeleton/pull/6#discussion_r889139130>
> :
>
> > +  .footer-top {
>
> +    display: flex;
>
> +    flex-direction: row;
>
> +  }
>
> +
>
> +  form {
>
> +    padding-top: 5%;
>
> +    width: 70%;
>
> +  }
>
> +}
>
>
>
>    - Your form margin/padding is not symmetrical. Kindly use the same
>    dimensions the Figma template provides.
>    [image: image]
>    <https://user-images.githubusercontent.com/61919617/171908231-9af5f93a-a06f-4d38-a015-015d114adc56.png>
>    [image: image]
>    <https://user-images.githubusercontent.com/61919617/171908308-5f212d77-7a7b-4df9-9bd5-27e5b0a84e0c.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Maria18000/Portfolio--setup-and-mobile-version-skeleton/pull/6#pullrequestreview-995179395>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVZIN6FH7TLJNGU5UDXOGALVNIYTXANCNFSM5XZMLGSA>
> .
> You are receiving this because you were mentioned.Message ID:
> <Maria18000/Portfolio--setup-and-mobile-version-skeleton/pull/6/review/995179395
> @github.com>
>

2022-06-04 15:42 UTC, algerina approved these changes
Hi @Maria18000 , 
Good job so far! :fire: 

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed :heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR, however you can improve it:heavy_check_mark:
- Your project looks awesome:heavy_check_mark:

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous TSEs
 
<img src="https://media1.giphy.com/media/3o7abKhOpu0NwenH3O/giphy.gif"/>
 ## Optional suggestions
 
 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-06-04 15:44 UTC, merged